# Ryan Kubanyi
## week13: 4/23026
### PANDAS Grouping Mapping Applying

In [2]:
import numpy as np
import pandas as pd
from pandas import *
from numpy.random import random, randn, randint

In [5]:
df = DataFrame(
        {'Qu1':np.random.choice(np.arange(10,101,10),size=5).astype(int),
         'Qu2':np.random.choice(np.arange(10,101,10),size=5).astype(int),
         'Qu3':np.random.choice(np.arange(10,101,10),size=5).astype(int),
         'Qu4':np.random.choice(np.arange(10,101,10),size=5).astype(int),
         'Qu5':np.random.choice(np.arange(10,101,10),size=5).astype(int)
        },
    index=["Student_" + ch for ch in "abcde"]
)

In [6]:
df.values

array([[ 70,  10,  30,  30, 100],
       [ 80, 100,  60,  70,  60],
       [ 30,  50,  90,  20,  30],
       [ 10,  10, 100,  20,  80],
       [ 20, 100, 100,  10,  60]])

In [7]:
df['Qu1'].value_counts()

70    1
20    1
10    1
30    1
80    1
Name: Qu1, dtype: int64

In [8]:
df.apply(value_counts) #apply()

     Qu1  Qu2  Qu3  Qu4  Qu5
10   1.0  2.0  NaN  1.0  NaN
20   1.0  NaN  NaN  2.0  NaN
30   1.0  NaN  1.0  1.0  1.0
50   NaN  1.0  NaN  NaN  NaN
60   NaN  NaN  1.0  NaN  2.0
70   1.0  NaN  NaN  1.0  NaN
80   1.0  NaN  NaN  NaN  1.0
90   NaN  NaN  1.0  NaN  NaN
100  NaN  2.0  2.0  NaN  1.0

In [9]:
df.loc['Student_c'].value_counts()

30    2
90    1
20    1
50    1
Name: Student_c, dtype: int64

In [11]:
rs = df.apply(value_counts).fillna(0).astype(int)
rs

     Qu1  Qu2  Qu3  Qu4  Qu5
10     1    2    0    1    0
20     1    0    0    2    0
30     1    0    1    1    1
50     0    1    0    0    0
60     0    0    1    0    2
70     1    0    0    1    0
80     1    0    0    0    1
90     0    0    1    0    0
100    0    2    2    0    1

In [12]:
rs.index.name='scores'
rs

        Qu1  Qu2  Qu3  Qu4  Qu5
scores
10        1    2    0    1    0
20        1    0    0    2    0
30        1    0    1    1    1
50        0    1    0    0    0
60        0    0    1    0    2
70        1    0    0    1    0
80        1    0    0    0    1
90        0    0    1    0    0
100       0    2    2    0    1

In [13]:
rs.columns.name='Questions'
rs

Questions  Qu1  Qu2  Qu3  Qu4  Qu5
scores
10           1    2    0    1    0
20           1    0    0    2    0
30           1    0    1    1    1
50           0    1    0    0    0
60           0    0    1    0    2
70           1    0    0    1    0
80           1    0    0    0    1
90           0    0    1    0    0
100          0    2    2    0    1

In [15]:
# dataset of customer orders
sample_product = ['T-shirt','Blouse','Jacket','Hoodie']
sample_color = ['Red','Orange','Yellow','Green','Blue']
sample_size = ['XS','S','M','L']

data = {
    
    'Order_ID:': np.random.choice(np.arange(500,5001,10),size=60).astype(int),
    'Product': np.random.choice(sample_product,size=60),
    'Color': np.random.choice(sample_color,size=60),
    'Size': np.random.choice(sample_size,size=60),
    'Date': pd.date_range(start='02-20-2026',periods=60)
}

df = DataFrame(data)
df

    Order_ID:  Product   Color Size       Date
0        1740   Jacket    Blue   XS 2026-02-20
1        3890   Hoodie   Green   XS 2026-02-21
2        1390   Blouse   Green    M 2026-02-22
3        2500   Hoodie    Blue    M 2026-02-23
4        1640  T-shirt   Green    S 2026-02-24
5         930   Blouse  Yellow    L 2026-02-25
6        1600   Jacket     Red    L 2026-02-26
7        2240   Hoodie    Blue    L 2026-02-27
8        3490   Blouse     Red    S 2026-02-28
9        2810  T-shirt     Red   XS 2026-03-01
10       2120   Jacket   Green    S 2026-03-02
11        820   Blouse  Yellow   XS 2026-03-03
12       2100   Blouse  Orange   XS 2026-03-04
13       2230   Jacket  Orange    M 2026-03-05
14       2740   Hoodie    Blue    M 2026-03-06
15       2310   Hoodie   Green    S 2026-03-07
16       4450   Blouse  Yellow    M 2026-03-08
17       3660   Jacket    Blue    L 2026-03-09
18       2600   Hoodie     Red    L 2026-03-10
19       4370   Blouse  Orange    M 2026-03-11
20       2690   Hoodie     Red    L 2026-03-12
21       4140   Jacket    Blue    L 2026-03-13
22        840   Blouse     Red   XS 2026-03-14
23       2120   Hoodie  Yellow   XS 2026-03-15
24       4970   Blouse   Green    M 2026-03-16
25        670   Blouse  Orange    M 2026-03-17
26       2400   Jacket     Red    M 2026-03-18
27       4070  T-shirt  Orange    S 2026-03-19
28        550  T-shirt     Red    L 2026-03-20
29       4740   Jacket  Orange    S 2026-03-21
30       1060  T-shirt  Orange   XS 2026-03-22
31       3620  T-shirt     Red    L 2026-03-23
32       3560   Blouse   Green    M 2026-03-24
33        890   Jacket  Yellow    M 2026-03-25
34       3890  T-shirt  Yellow    M 2026-03-26
35       2370   Hoodie     Red   XS 2026-03-27
36       3050  T-shirt   Green   XS 2026-03-28
37       1870   Hoodie   Green   XS 2026-03-29
38       1110   Jacket     Red   XS 2026-03-30
39       3560   Jacket  Yellow    S 2026-03-31
40       3820   Hoodie    Blue   XS 2026-04-01
41       2100  T-shirt     Red    L 2026-04-02
42        910   Blouse   Green    L 2026-04-03
43       3920   Blouse  Orange   XS 2026-04-04
44       1590   Blouse  Yellow    S 2026-04-05
45       4750   Hoodie    Blue   XS 2026-04-06
46       1960   Jacket   Green    S 2026-04-07
47       4370  T-shirt  Yellow    M 2026-04-08
48       4120  T-shirt   Green    S 2026-04-09
49       3850   Blouse     Red    M 2026-04-10
50       1800  T-shirt     Red   XS 2026-04-11
51       1890   Blouse     Red   XS 2026-04-12
52        750   Jacket  Orange    S 2026-04-13
53       2050   Hoodie    Blue    S 2026-04-14
54       1870   Blouse  Orange    S 2026-04-15
55        780  T-shirt  Yellow    S 2026-04-16
56       3340   Hoodie     Red    S 2026-04-17
57       3070   Hoodie   Green   XS 2026-04-18
58       3390  T-shirt  Yellow   XS 2026-04-19
59       2450   Blouse  Yellow    M 2026-04-20

In [16]:
df.set_index('Date',inplace=True)
df

            Order_ID:  Product   Color Size
Date
2026-02-20       1740   Jacket    Blue   XS
2026-02-21       3890   Hoodie   Green   XS
2026-02-22       1390   Blouse   Green    M
2026-02-23       2500   Hoodie    Blue    M
2026-02-24       1640  T-shirt   Green    S
2026-02-25        930   Blouse  Yellow    L
2026-02-26       1600   Jacket     Red    L
2026-02-27       2240   Hoodie    Blue    L
2026-02-28       3490   Blouse     Red    S
2026-03-01       2810  T-shirt     Red   XS
2026-03-02       2120   Jacket   Green    S
2026-03-03        820   Blouse  Yellow   XS
2026-03-04       2100   Blouse  Orange   XS
2026-03-05       2230   Jacket  Orange    M
2026-03-06       2740   Hoodie    Blue    M
2026-03-07       2310   Hoodie   Green    S
2026-03-08       4450   Blouse  Yellow    M
2026-03-09       3660   Jacket    Blue    L
2026-03-10       2600   Hoodie     Red    L
2026-03-11       4370   Blouse  Orange    M
2026-03-12       2690   Hoodie     Red    L
2026-03-13       4140   Jacket    Blue    L
2026-03-14        840   Blouse     Red   XS
2026-03-15       2120   Hoodie  Yellow   XS
2026-03-16       4970   Blouse   Green    M
2026-03-17        670   Blouse  Orange    M
2026-03-18       2400   Jacket     Red    M
2026-03-19       4070  T-shirt  Orange    S
2026-03-20        550  T-shirt     Red    L
2026-03-21       4740   Jacket  Orange    S
2026-03-22       1060  T-shirt  Orange   XS
2026-03-23       3620  T-shirt     Red    L
2026-03-24       3560   Blouse   Green    M
2026-03-25        890   Jacket  Yellow    M
2026-03-26       3890  T-shirt  Yellow    M
2026-03-27       2370   Hoodie     Red   XS
2026-03-28       3050  T-shirt   Green   XS
2026-03-29       1870   Hoodie   Green   XS
2026-03-30       1110   Jacket     Red   XS
2026-03-31       3560   Jacket  Yellow    S
2026-04-01       3820   Hoodie    Blue   XS
2026-04-02       2100  T-shirt     Red    L
2026-04-03        910   Blouse   Green    L
2026-04-04       3920   Blouse  Orange   XS
2026-04-05       1590   Blouse  Yellow    S
2026-04-06       4750   Hoodie    Blue   XS
2026-04-07       1960   Jacket   Green    S
2026-04-08       4370  T-shirt  Yellow    M
2026-04-09       4120  T-shirt   Green    S
2026-04-10       3850   Blouse     Red    M
2026-04-11       1800  T-shirt     Red   XS
2026-04-12       1890   Blouse     Red   XS
2026-04-13        750   Jacket  Orange    S
2026-04-14       2050   Hoodie    Blue    S
2026-04-15       1870   Blouse  Orange    S
2026-04-16        780  T-shirt  Yellow    S
2026-04-17       3340   Hoodie     Red    S
2026-04-18       3070   Hoodie   Green   XS
2026-04-19       3390  T-shirt  Yellow   XS
2026-04-20       2450   Blouse  Yellow    M

In [17]:
df['Product'].value_counts()

Blouse     18
Hoodie     15
T-shirt    14
Jacket     13
Name: Product, dtype: int64

In [19]:
df = DataFrame({'City': ['Alma','Brian Head','Fox Park','Lake Mary'],
                'altitude':[100,200,300,1000]})
df

         City  altitude
0        Alma       100
1  Brian Head       200
2    Fox Park       300
3   Lake Mary      1000

In [22]:
st = {'Alma':'Colorado',
      'Brian Head':'Utah',
      'Fox Park':'Wyoming',
      'Lake Mary':'California'
     }
df

         City  altitude
0        Alma       100
1  Brian Head       200
2    Fox Park       300
3   Lake Mary      1000

In [24]:
df_copy = df.copy()

df['altitude'] = df['altitude'].apply(lambda x: x/3.2808)
df

         City   altitude
0        Alma   9.290530
1  Brian Head  18.581060
2    Fox Park  27.871590
3   Lake Mary  92.905299

In [25]:
df['altitude'] = df['altitude'].apply(lambda x: x/3.2808)
df

         City   altitude
0        Alma   2.831788
1  Brian Head   5.663576
2    Fox Park   8.495364
3   Lake Mary  28.317880

In [28]:
#groupby


cars = ['Toyota','GMC','Ford','Dodge']

df = DataFrame({
    'brand': np.random.choice(cars, size=20),
    'price': np.random.randint(40000,65000,size=20),
    'Sales_Data': pd.date_range(start='04-01-2026',periods=20)
})

df.set_index('Sales_Data', inplace=True)
df

             brand  price
Sales_Data
2026-04-01    Ford  42331
2026-04-02    Ford  59411
2026-04-03  Toyota  43119
2026-04-04     GMC  51576
2026-04-05  Toyota  50476
2026-04-06    Ford  59779
2026-04-07   Dodge  60902
2026-04-08   Dodge  46723
2026-04-09     GMC  64172
2026-04-10   Dodge  41146
2026-04-11   Dodge  51981
2026-04-12    Ford  44562
2026-04-13    Ford  45082
2026-04-14   Dodge  51771
2026-04-15   Dodge  52138
2026-04-16   Dodge  46338
2026-04-17   Dodge  56544
2026-04-18    Ford  40923
2026-04-19    Ford  47632
2026-04-20  Toyota  53825

In [31]:
df.groupby('brand').count()
df

             brand  price
Sales_Data
2026-04-01    Ford  42331
2026-04-02    Ford  59411
2026-04-03  Toyota  43119
2026-04-04     GMC  51576
2026-04-05  Toyota  50476
2026-04-06    Ford  59779
2026-04-07   Dodge  60902
2026-04-08   Dodge  46723
2026-04-09     GMC  64172
2026-04-10   Dodge  41146
2026-04-11   Dodge  51981
2026-04-12    Ford  44562
2026-04-13    Ford  45082
2026-04-14   Dodge  51771
2026-04-15   Dodge  52138
2026-04-16   Dodge  46338
2026-04-17   Dodge  56544
2026-04-18    Ford  40923
2026-04-19    Ford  47632
2026-04-20  Toyota  53825

In [32]:
df.groupby('brand').mean()

               price
brand
Dodge   50942.875000
Ford    48531.428571
GMC     57874.000000
Toyota  49140.000000

In [33]:
df['price'].groupby(df['brand']).sum()

brand
Dodge     407543
Ford      339720
GMC       115748
Toyota    147420
Name: price, dtype: int32

In [34]:
df['cum_sum'] = df.groupby('brand')['price'].cumsum()
df

             brand  price  cum_sum
Sales_Data
2026-04-01    Ford  42331    42331
2026-04-02    Ford  59411   101742
2026-04-03  Toyota  43119    43119
2026-04-04     GMC  51576    51576
2026-04-05  Toyota  50476    93595
2026-04-06    Ford  59779   161521
2026-04-07   Dodge  60902    60902
2026-04-08   Dodge  46723   107625
2026-04-09     GMC  64172   115748
2026-04-10   Dodge  41146   148771
2026-04-11   Dodge  51981   200752
2026-04-12    Ford  44562   206083
2026-04-13    Ford  45082   251165
2026-04-14   Dodge  51771   252523
2026-04-15   Dodge  52138   304661
2026-04-16   Dodge  46338   350999
2026-04-17   Dodge  56544   407543
2026-04-18    Ford  40923   292088
2026-04-19    Ford  47632   339720
2026-04-20  Toyota  53825   147420

In [38]:
df.groupby(['k1','k2']).mean()

KeyError: 'k1'