# Ryan Kubanyi
## week13: 4/16/2026
### PANDAS Processing DataFrame

In [1]:
import numpy as np
import pandas as pd
from numpy.random import *
from pandas import *

In [2]:
#Drop entries
df = DataFrame(np.arange(1,17).reshape((4,4)),
              columns = ['one','two','three','four'],
               index = ['ohio','colorado','utah','new york']
              )
df

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [4]:
df_index_name = 'colorado'

In [6]:
df.drop(['colorado'])

          one  two  three  four
ohio        1    2      3     4
utah        9   10     11    12
new york   13   14     15    16

In [7]:
df.drop(['three'],axis='columns')

          one  two  four
ohio        1    2     4
colorado    5    6     8
utah        9   10    12
new york   13   14    16

In [8]:
df1 = df.copy()
df1

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [9]:
df

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [10]:
df1

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [11]:
df1[df1<4] = 0
df1

          one  two  three  four
ohio        0    0      0     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [12]:
# alignment of data
df1 = DataFrame(np.arange(9).reshape(3,3), columns=list('bcd'),
               index = ['Ohio','Texas','Colorado']
               )
df2 = DataFrame(np.arange(12).reshape(4,3), columns=list('bde'),
               index = ['Utah','Ohio','Texas','Oregon']
              )

In [13]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [14]:
df2

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [17]:
df1.add(df2,fill_value=0) # fill_value=: number + 0 (instead of number + NaN which = NaN)

            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [18]:
df1['e'] = df1['b'] + df1['d']
df1

          b  c  d   e
Ohio      0  1  2   2
Texas     3  4  5   8
Colorado  6  7  8  14

In [23]:
#Sort and Rank
df = DataFrame(np.random.choice(np.arange(1,21),size = 8).reshape(2,4),
               columns = list('dabd'),
               index=['three','one'])
df

        d  a  b   d
three  11  7  7  19
one     1  6  3   7

In [24]:
df.sort_index()

        d  a  b   d
one     1  6  3   7
three  11  7  7  19

In [25]:
df

        d  a  b   d
three  11  7  7  19
one     1  6  3   7

In [26]:
df.sort_index(axis=1)

       a  b   d   d
three  7  7  11  19
one    6  3   1   7

In [27]:
df.sort_index(axis=1,ascending=False)

        d   d  b  a
three  11  19  7  7
one     1   7  3  6

In [28]:
# Sort by values
df.sort_values(by='b')

        d  a  b   d
one     1  6  3   7
three  11  7  7  19

In [30]:
df = DataFrame(np.random.choice(np.arange(-10,21),size = 16).reshape(4,4),
               columns = list('dabc'),
               index=['three','one','four','seven'])
df

        d   a   b   c
three  14  16   7  -8
one    -2  14   7  16
four    7  -7  -2   8
seven -10   4  14  12

In [33]:
df.mean()

d    2.25
a    6.75
b    6.50
c    7.00
dtype: float64

In [34]:
df.sort_values(by='c')

        d   a   b   c
three  14  16   7  -8
four    7  -7  -2   8
seven -10   4  14  12
one    -2  14   7  16

In [35]:
df.sort_values(by=['a','d'])

        d   a   b   c
four    7  -7  -2   8
seven -10   4  14  12
one    -2  14   7  16
three  14  16   7  -8

In [36]:
df.sort_values(by='seven',axis=1)

        d   a   c   b
three  14  16  -8   7
one    -2  14  16   7
four    7  -7   8  -2
seven -10   4  12  14

In [37]:
df.rank().astype(int)

       d  a  b  c
three  4  4  2  1
one    2  3  2  4
four   3  1  1  2
seven  1  2  4  3

In [39]:
df['e'] = np.where(df['c'] > 2, df['c'],np.nan)
df

        d   a   b   c     e
three  14  16   7  -8   NaN
one    -2  14   7  16  16.0
four    7  -7  -2   8   8.0
seven -10   4  14  12  12.0

In [40]:
df.sum()

d     9.0
a    27.0
b    26.0
c    28.0
e    36.0
dtype: float64

In [41]:
df.sum(axis=1)

three    29.0
one      51.0
four     14.0
seven    32.0
dtype: float64

In [47]:
df.mean(axis=1,skipna=False)

three     NaN
one      10.2
four      2.8
seven     6.4
dtype: float64

In [48]:
df.max()

d    14.0
a    16.0
b    14.0
c    16.0
e    16.0
dtype: float64