# Ryan Kubanyi
## week13: 4/16/2026
### PANDAS Processing DataFrame

In [1]:
import numpy as np
import pandas as pd
from numpy.random import *
from pandas import *

In [2]:
#Drop entries
df = DataFrame(np.arange(1,17).reshape((4,4)),
              columns = ['one','two','three','four'],
               index = ['ohio','colorado','utah','new york']
              )
df

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [3]:
df_index_name = 'colorado'

In [4]:
df.drop(['colorado'])

          one  two  three  four
ohio        1    2      3     4
utah        9   10     11    12
new york   13   14     15    16

In [5]:
df.drop(['three'],axis='columns')

          one  two  four
ohio        1    2     4
colorado    5    6     8
utah        9   10    12
new york   13   14    16

In [6]:
df1 = df.copy()
df1

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [7]:
df

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [8]:
df1

          one  two  three  four
ohio        1    2      3     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [9]:
df1[df1<4] = 0
df1

          one  two  three  four
ohio        0    0      0     4
colorado    5    6      7     8
utah        9   10     11    12
new york   13   14     15    16

In [10]:
# alignment of data
df1 = DataFrame(np.arange(9).reshape(3,3), columns=list('bcd'),
               index = ['Ohio','Texas','Colorado']
               )
df2 = DataFrame(np.arange(12).reshape(4,3), columns=list('bde'),
               index = ['Utah','Ohio','Texas','Oregon']
              )

In [11]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [12]:
df2

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [13]:
df1.add(df2,fill_value=0) # fill_value=: number + 0 (instead of number + NaN which = NaN)

            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [14]:
df1['e'] = df1['b'] + df1['d']
df1

          b  c  d   e
Ohio      0  1  2   2
Texas     3  4  5   8
Colorado  6  7  8  14

In [15]:
#Sort and Rank
df = DataFrame(np.random.choice(np.arange(1,21),size = 8).reshape(2,4),
               columns = list('dabd'),
               index=['three','one'])
df

        d   a   b   d
three  20   4  19  14
one    11  11  17  18

In [16]:
df.sort_index()

        d   a   b   d
one    11  11  17  18
three  20   4  19  14

In [17]:
df

        d   a   b   d
three  20   4  19  14
one    11  11  17  18

In [18]:
df.sort_index(axis=1)

        a   b   d   d
three   4  19  20  14
one    11  17  11  18

In [19]:
df.sort_index(axis=1,ascending=False)

        d   d   b   a
three  20  14  19   4
one    11  18  17  11

In [20]:
# Sort by values
df.sort_values(by='b')

        d   a   b   d
one    11  11  17  18
three  20   4  19  14

In [21]:
df = DataFrame(np.random.choice(np.arange(-10,21),size = 16).reshape(4,4),
               columns = list('dabc'),
               index=['three','one','four','seven'])
df

       d   a   b   c
three  3  -6   4  20
one    9  15  -3  11
four  -7  17  17  12
seven  9  -4  13  -1

In [22]:
df.mean()

d     3.50
a     5.50
b     7.75
c    10.50
dtype: float64

In [23]:
df.sort_values(by='c')

       d   a   b   c
seven  9  -4  13  -1
one    9  15  -3  11
four  -7  17  17  12
three  3  -6   4  20

In [24]:
df.sort_values(by=['a','d'])

       d   a   b   c
three  3  -6   4  20
seven  9  -4  13  -1
one    9  15  -3  11
four  -7  17  17  12

In [25]:
df.sort_values(by='seven',axis=1)

        a   c  d   b
three  -6  20  3   4
one    15  11  9  -3
four   17  12 -7  17
seven  -4  -1  9  13

In [26]:
df.rank().astype(int)

       d  a  b  c
three  2  1  2  4
one    3  3  1  2
four   1  4  4  3
seven  3  2  3  1

In [27]:
df['e'] = np.where(df['c'] > 2, df['c'],np.nan)
df

       d   a   b   c     e
three  3  -6   4  20  20.0
one    9  15  -3  11  11.0
four  -7  17  17  12  12.0
seven  9  -4  13  -1   NaN

In [28]:
df.sum()

d    14.0
a    22.0
b    31.0
c    42.0
e    43.0
dtype: float64

In [29]:
df.sum(axis=1)

three    41.0
one      43.0
four     51.0
seven    17.0
dtype: float64

In [30]:
df.mean(axis=1,skipna=False)

three     8.2
one       8.6
four     10.2
seven     NaN
dtype: float64

In [31]:
df.max()

d     9.0
a    17.0
b    17.0
c    20.0
e    20.0
dtype: float64

In [33]:
df = DataFrame([np.random.choice(np.arange(-5,5),size=5),np.random.choice(np.arange(-5,5),size=5),np.random.choice(np.arange(-5,5),size=5),np.random.choice(np.arange(-5,5),size=5)],
              index=list('abcd'),
              columns=['one','two','three','four','five'])
df

   one  two  three  four  five
a    2    4     -5    -5     3
b   -3    4     -4    -4     0
c    4   -2     -5    -4     4
d   -1    2     -5     0     3

In [34]:
df.idxmax()

one      c
two      a
three    b
four     d
five     c
dtype: object

In [35]:
df.idxmax(axis=1)

a     two
b     two
c     one
d    five
dtype: object

In [36]:
df.idxmin()

one      b
two      c
three    a
four     a
five     b
dtype: object

In [37]:
df

   one  two  three  four  five
a    2    4     -5    -5     3
b   -3    4     -4    -4     0
c    4   -2     -5    -4     4
d   -1    2     -5     0     3

In [39]:
#Create a DataFrame representing stock prices
data = {
    'Date': pd.date_range(start='2026-01-01', end='2026-01-10'),
    'META': np.random.choice(np.arange(100,300),size=10),
    'TSLA': np.random.choice(np.arange(100,300),size=10),
    'GOOGL': np.random.choice(np.arange(100,300),size=10)
}
data

{'Date': DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
                '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
                '2026-01-09', '2026-01-10'],
               dtype='datetime64[ns]', freq='D'),
 'META': array([193, 245, 124, 273, 172, 240, 219, 224, 237, 122]),
 'TSLA': array([286, 206, 131, 265, 223, 164, 163, 176, 233, 103]),
 'GOOGL': array([272, 109, 148, 154, 192, 252, 116, 298, 266, 213])}

In [41]:
df = DataFrame(data, index=data['Date'])
df

                 Date  META  TSLA  GOOGL
2026-01-01 2026-01-01   193   286    272
2026-01-02 2026-01-02   245   206    109
2026-01-03 2026-01-03   124   131    148
2026-01-04 2026-01-04   273   265    154
2026-01-05 2026-01-05   172   223    192
2026-01-06 2026-01-06   240   164    252
2026-01-07 2026-01-07   219   163    116
2026-01-08 2026-01-08   224   176    298
2026-01-09 2026-01-09   237   233    266
2026-01-10 2026-01-10   122   103    213

In [42]:
df = DataFrame(data, index=data['Date'], columns=['META','TSLA','GOOGL'])
df

            META  TSLA  GOOGL
2026-01-01   193   286    272
2026-01-02   245   206    109
2026-01-03   124   131    148
2026-01-04   273   265    154
2026-01-05   172   223    192
2026-01-06   240   164    252
2026-01-07   219   163    116
2026-01-08   224   176    298
2026-01-09   237   233    266
2026-01-10   122   103    213

In [43]:
#Find the date with the highest closing price for each stock
df.idxmax()

META    2026-01-04
TSLA    2026-01-01
GOOGL   2026-01-08
dtype: datetime64[ns]

In [44]:
df.idxmin()

META    2026-01-10
TSLA    2026-01-10
GOOGL   2026-01-02
dtype: datetime64[ns]

In [47]:
df_t = df.T

In [48]:
# Find the stock with the minimum and maximum values for a specific date: 1/2/26
df_t['2026-01-02'].idxmax()

'META'

In [49]:
df_t['2026-01-02'].idxmin()

'GOOGL'

In [50]:
df.dropna(axis=1)

            META  TSLA  GOOGL
2026-01-01   193   286    272
2026-01-02   245   206    109
2026-01-03   124   131    148
2026-01-04   273   265    154
2026-01-05   172   223    192
2026-01-06   240   164    252
2026-01-07   219   163    116
2026-01-08   224   176    298
2026-01-09   237   233    266
2026-01-10   122   103    213

In [51]:
# Using thresh to keep only the rows having two or more valid data
df.dropna(thresh=2)

            META  TSLA  GOOGL
2026-01-01   193   286    272
2026-01-02   245   206    109
2026-01-03   124   131    148
2026-01-04   273   265    154
2026-01-05   172   223    192
2026-01-06   240   164    252
2026-01-07   219   163    116
2026-01-08   224   176    298
2026-01-09   237   233    266
2026-01-10   122   103    213

In [52]:
df.fillna(0)

            META  TSLA  GOOGL
2026-01-01   193   286    272
2026-01-02   245   206    109
2026-01-03   124   131    148
2026-01-04   273   265    154
2026-01-05   172   223    192
2026-01-06   240   164    252
2026-01-07   219   163    116
2026-01-08   224   176    298
2026-01-09   237   233    266
2026-01-10   122   103    213

In [53]:
df.ffill()

            META  TSLA  GOOGL
2026-01-01   193   286    272
2026-01-02   245   206    109
2026-01-03   124   131    148
2026-01-04   273   265    154
2026-01-05   172   223    192
2026-01-06   240   164    252
2026-01-07   219   163    116
2026-01-08   224   176    298
2026-01-09   237   233    266
2026-01-10   122   103    213