# Ryan Kubanyi
## week13: 4/14/2026
### PANDAS

In [1]:
import numpy as np
from numpy.random import randn, random
import pandas as pd
from pandas import Series, DataFrame # * to import everything

In [2]:
s = Series(randn(15) * 10)
s

0      5.569695
1    -12.495529
2     -5.666404
3     -8.653618
4      1.112701
5     -0.973479
6     23.664574
7     18.600594
8     21.073919
9      0.890161
10    13.653704
11     3.111202
12   -10.442598
13   -10.464075
14    -0.491057
dtype: float64

In [3]:
s.index

RangeIndex(start=0, stop=15, step=1)

In [4]:
s.values

array([  5.56969497, -12.49552917,  -5.66640423,  -8.65361841,
         1.11270098,  -0.97347948,  23.66457424,  18.60059432,
        21.07391877,   0.89016137,  13.65370436,   3.11120209,
       -10.4425981 , -10.46407488,  -0.49105655])

In [6]:
s[14]

-0.49105655294904793

In [8]:
#Create Labels
s = Series(np.arange(10,15), index=['w','x','y','z','t'])
s

w    10
x    11
y    12
z    13
t    14
dtype: int32

In [9]:
so = Series([2520,1122,937,847,713], index = ['USA','Russia','Germany','UK','France'])
so

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [10]:
so['USA']

2520

In [11]:
so[so > 800]

USA        2520
Russia     1122
Germany     937
UK          847
dtype: int64

In [12]:
so > 800

USA         True
Russia      True
Germany     True
UK          True
France     False
dtype: bool

In [13]:
#Convert Series to Dictionary
d = dict(so)
d

{'USA': 2520, 'Russia': 1122, 'Germany': 937, 'UK': 847, 'France': 713}

In [14]:
s2 = Series(d)
s2

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [17]:
# merge
country = ['USA','Russia','Germany','UK','France','Spain','Italy']
country

['USA', 'Russia', 'Germany', 'UK', 'France', 'Spain', 'Italy']

In [18]:
s2 = Series(d, index=country)
s2

USA        2520.0
Russia     1122.0
Germany     937.0
UK          847.0
France      713.0
Spain         NaN
Italy         NaN
dtype: float64

In [19]:
so

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [20]:
s2

USA        2520.0
Russia     1122.0
Germany     937.0
UK          847.0
France      713.0
Spain         NaN
Italy         NaN
dtype: float64

In [21]:
so+s2

France     1426.0
Germany    1874.0
Italy         NaN
Russia     2244.0
Spain         NaN
UK         1694.0
USA        5040.0
dtype: float64

In [22]:
s2.name = "Summer Olympic"
s2

USA        2520.0
Russia     1122.0
Germany     937.0
UK          847.0
France      713.0
Spain         NaN
Italy         NaN
Name: Summer Olympic, dtype: float64

In [23]:
s2.index.name = 'Country'
s2

Country
USA        2520.0
Russia     1122.0
Germany     937.0
UK          847.0
France      713.0
Spain         NaN
Italy         NaN
Name: Summer Olympic, dtype: float64

In [24]:
# Dataframe: is a 2 dimensional array
d = {
    "calories": [420,380,390],
    "fruits": ['Orange','Banana','Grape']
}
d

{'calories': [420, 380, 390], 'fruits': ['Orange', 'Banana', 'Grape']}

In [25]:
df = DataFrame(d)
df

   calories  fruits
0       420  Orange
1       380  Banana
2       390   Grape

In [26]:
df['calories']

0    420
1    380
2    390
Name: calories, dtype: int64

In [27]:
df['fruits']

0    Orange
1    Banana
2     Grape
Name: fruits, dtype: object

In [28]:
# Locate Row
df.loc[0]

calories       420
fruits      Orange
Name: 0, dtype: object

In [30]:
df.loc[2]

calories      390
fruits      Grape
Name: 2, dtype: object

In [31]:
type(df)

pandas.core.frame.DataFrame

In [32]:
df.loc[[0,2]]

   calories  fruits
0       420  Orange
2       390   Grape

In [34]:
df.loc[[2,1]]

   calories  fruits
2       390   Grape
1       380  Banana

In [37]:
df2 = DataFrame({
    'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
    'year': [2000,2001,2002,2001,2002,2003],
    'pop': [1.5,1.7,3.6,2.4,2.9,3.2]
})
df2

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
df2.head(3)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [39]:
df2.tail(2)

    state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [41]:
df3 = DataFrame(df2, columns=['year','state','pop'])
df3

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [42]:
df4 = DataFrame({
    'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
    'year': [2000,2001,2002,2001,2002,2003],
    'pop': [1.5,1.7,3.6,2.4,2.9,3.2]
},
    columns=['year','state','pop'],
    index=['one','two','three','four','five','six'])
df4

       year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [43]:
df4.columns

Index(['year', 'state', 'pop'], dtype='object')

In [44]:
df4['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [45]:
df4.loc['three']

year     2002
state    Ohio
pop       3.6
Name: three, dtype: object

In [46]:
df4.iloc[0]

year     2000
state    Ohio
pop       1.5
Name: one, dtype: object

In [47]:
#add a new column
df4['debt'] = 10
df4

       year   state  pop  debt
one    2000    Ohio  1.5    10
two    2001    Ohio  1.7    10
three  2002    Ohio  3.6    10
four   2001  Nevada  2.4    10
five   2002  Nevada  2.9    10
six    2003  Nevada  3.2    10

In [49]:
df4['debt'] = random(len(df4['debt'])) * 10
df4

       year   state  pop      debt
one    2000    Ohio  1.5  7.962956
two    2001    Ohio  1.7  3.545868
three  2002    Ohio  3.6  3.005320
four   2001  Nevada  2.4  7.218830
five   2002  Nevada  2.9  6.012468
six    2003  Nevada  3.2  3.854858

In [50]:
df4['eastern'] = df4['state'] == 'Ohio'
df4

       year   state  pop      debt  eastern
one    2000    Ohio  1.5  7.962956     True
two    2001    Ohio  1.7  3.545868     True
three  2002    Ohio  3.6  3.005320     True
four   2001  Nevada  2.4  7.218830    False
five   2002  Nevada  2.9  6.012468    False
six    2003  Nevada  3.2  3.854858    False

In [51]:
df4[df4['pop'] > 2]

       year   state  pop      debt  eastern
three  2002    Ohio  3.6  3.005320     True
four   2001  Nevada  2.4  7.218830    False
five   2002  Nevada  2.9  6.012468    False
six    2003  Nevada  3.2  3.854858    False

In [52]:
df4[df4['state'] == 'Nevada']

      year   state  pop      debt  eastern
four  2001  Nevada  2.4  7.218830    False
five  2002  Nevada  2.9  6.012468    False
six   2003  Nevada  3.2  3.854858    False

In [53]:
df4.T

             one      two    three     four     five      six
year        2000     2001     2002     2001     2002     2003
state       Ohio     Ohio     Ohio   Nevada   Nevada   Nevada
pop          1.5      1.7      3.6      2.4      2.9      3.2
debt     7.96296  3.54587  3.00532  7.21883  6.01247  3.85486
eastern     True     True     True    False    False    False